import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useDashboard } from '../hooks/useDashboard'
import { useConfig } from '../hooks/useConfig'
import { useScreenings } from '../hooks/useScreenings'
import { SCREENING_MAP, isDue } from '../lib/screenings'
import type { ScreeningFrequency } from '../lib/screenings'
import AppLogo from '../components/ui/AppLogo'

const MOOD_EMOJI = ['', '😞', '😕', '😐', '🙂', '😄']

type SummaryState =
  | { status: 'idle' }
  | { status: 'loading' }
  | { status: 'done'; text: string }
  | { status: 'error'; message: string }

function SummaryCard({ state, onRetry, model }: { state: SummaryState; onRetry: () => void; model: string }) {
  return (
    <div className="bg-[--color-surface-2] rounded-xl border border-[--color-border] p-4">
      <div className="flex items-center justify-between mb-2">
        <h2 className="text-xs font-semibold text-[--color-muted] uppercase tracking-wider">
          Today's Readiness
        </h2>
        {state.status === 'done' && (
          <button onClick={onRetry} className="text-[10px] text-[--color-muted] hover:text-white transition-colors">
            Refresh
          </button>
        )}
      </div>

      {state.status === 'loading' && (
        <p className="text-sm text-[--color-muted] animate-pulse">Generating summary…</p>
      )}

      {state.status === 'done' && (
        <div>
          <p className="text-sm leading-relaxed">{state.text}</p>
          <p className="text-[10px] text-[--color-muted] mt-2">Generated by {model} · local</p>
        </div>
      )}

      {state.status === 'error' && (
        <div className="flex items-start justify-between gap-3">
          <p className="text-xs text-[--color-muted]">{state.message}</p>
          <button
            onClick={onRetry}
            className="shrink-0 text-xs text-[--color-brand] hover:opacity-80 transition-opacity"
          >
            Retry
          </button>
        </div>
      )}
    </div>
  )
}

function MetricCard({ label, value, unit }: { label: string; value: string | number | null; unit?: string }) {
  return (
    <div className="flex-1 bg-[--color-surface-2] rounded-xl border border-[--color-border] p-3 flex flex-col gap-1">
      <span className="text-[--color-muted] text-xs">{label}</span>
      <span className="text-lg font-semibold">
        {value != null ? (
          <>
            {value}
            {unit && <span className="text-sm font-normal text-[--color-muted] ml-0.5">{unit}</span>}
          </>
        ) : (
          <span className="text-[--color-muted] text-sm">—</span>
        )}
      </span>
    </div>
  )
}


export default function Dashboard() {
  const navigate = useNavigate()
  const { today, hasCheckInToday, syncing, triggerSync } = useDashboard()
  const { config } = useConfig()
  const { results: screeningResults } = useScreenings()
  const [summary, setSummary] = useState<SummaryState>({ status: 'idle' })

  // Screenings that are currently due
  const dueScreenings = (config.screeningsEnabled ?? []).filter((id) => {
    const last = screeningResults.find((r) => r.type === id)
    return isDue(last?.date ?? null, (config.screeningFrequency ?? 'weekly') as ScreeningFrequency)
  })

  // Auto-sync on load if connected to Oura
  useEffect(() => {
    if (config.ouraAccessToken) {
      triggerSync()
    }
  }, [config.ouraAccessToken]) // eslint-disable-line react-hooks/exhaustive-deps

  const generateSummary = async (force = false) => {
    setSummary({ status: 'loading' })
    try {
      const text = await window.baseline.generateSummary(force)
      setSummary({ status: 'done', text })
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Could not generate summary.'
      setSummary({ status: 'error', message: msg })
    }
  }

  // Generate once on mount when summaries are enabled (cache handled in main process)
  useEffect(() => {
    if (config.ollamaSummariesEnabled) {
      generateSummary(false)
    }
  }, [config.ollamaSummariesEnabled]) // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="flex flex-col h-full">
      {/* Header */}
      <div className="drag-region px-5 pt-10 pb-3">
        <div className="no-drag flex items-center justify-between">
          <AppLogo width={108} />
          {syncing ? (
            <span className="text-[--color-muted] text-xs">Syncing…</span>
          ) : (
            <span className="text-[--color-muted] text-xs">
              {new Date().toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' })}
            </span>
          )}
        </div>
      </div>

      <div className="flex-1 overflow-y-auto px-5 flex flex-col gap-5 pb-6">
        {/* Today metrics */}
        <div className="flex gap-2">
          <MetricCard label="Readiness" value={today?.readiness_score ?? null} />
          <MetricCard label="HRV" value={today?.hrv_avg != null ? Math.round(today.hrv_avg) : null} />
          <MetricCard label="Sleep" value={today?.sleep_hours ?? null} unit="h" />
        </div>

        {/* Check-in CTA */}
        {!hasCheckInToday && (
          <button
            onClick={() => navigate('/check-in')}
            className="w-full py-3.5 rounded-xl bg-[--color-brand] text-white font-medium hover:opacity-90 transition-opacity text-sm"
          >
            Log today's check-in
          </button>
        )}

        {hasCheckInToday && today && (
          <div
            onClick={() => navigate('/check-in')}
            className="w-full py-3 rounded-xl bg-[--color-surface-2] border border-[--color-border] flex items-center justify-between px-4 cursor-pointer hover:border-[--color-brand] transition-colors"
          >
            <div className="flex items-center gap-3">
              <span className="text-2xl">{MOOD_EMOJI[today.mood!]}</span>
              <div>
                <p className="text-sm font-medium">Mood {today.mood}/5 · Energy {today.energy}/5</p>
                <p className="text-xs text-[--color-muted]">Today's log — tap to edit</p>
              </div>
            </div>
          </div>
        )}

        {/* Screening due notifications */}
        {dueScreenings.map((id) => (
          <button
            key={id}
            onClick={() => navigate(`/screening/${id}`)}
            className="w-full py-3 px-4 rounded-xl bg-[--color-surface-2] border border-[--color-brand]/40 flex items-center justify-between hover:border-[--color-brand] transition-colors"
          >
            <div className="flex items-center gap-3">
              <span className="text-xl">📋</span>
              <div className="text-left">
                <p className="text-sm font-medium">{id} due</p>
                <p className="text-xs text-[--color-muted]">
                  {SCREENING_MAP[id]
                    ? `${SCREENING_MAP[id].questions.length} questions · ~2 min`
                    : 'Tap to begin'}
                </p>
              </div>
            </div>
            <span className="text-[--color-muted] text-lg">›</span>
          </button>
        ))}

        {/* LLM readiness summary — only when enabled in Settings */}
        {config.ollamaSummariesEnabled && summary.status !== 'idle' && (
          <SummaryCard
            state={summary}
            onRetry={() => generateSummary(true)}
            model={config.ollamaModel || 'llama3.2'}
          />
        )}

      </div>
    </div>
  )
}
